### PR TITLE
Copyedit suggestions for the intro's async await section

### PR DESCRIPTION
**Pull request by rrelledge**
@MeirShpilraien, here are some copyedit suggestions.

### CODE REVIEW

**Review by chayim — APPROVED** [review]

**Comment by MeirShpilraien** [comment]
@rrelledge can you please accept the license/cla so we can merge? thanks.

**Comment by rrelledge** [comment]
> @rrelledge can you please accept the license/cla so we can merge? thanks.

For me, it says that I've already signed it and won't let me do anything else. I'm not sure why it still says "Waiting for status to be reported" in the main checklist.

**Comment by rrelledge** [comment]
> @rrelledge can you please accept the license/cla so we can merge? thanks.

For me, it says that I've already signed it and won't let me do anything else. I'm not sure why it still says "Waiting for status to be reported" in the main checklist.

**Comment by MeirShpilraien** [comment]
@chayim @gkorland any idea how to fix it?

**Comment by chayim** [comment]
Sometimes it gets stuck. I can merge override.

**Pull request merged**
