### PR TITLE
Use safe lock in RedisAI initialization

### PR DESCRIPTION
**Pull request by alonre24**

### CODE REVIEW

**Review by MeirShpilraien — APPROVED** [review]
@alonre24 do we need to backport it to 1.0? If so please open a PR.

**Comment by alonre24** [comment]
> @alonre24 do we need to backport it to 1.0? If so please open a PR.
As far as I understand we don't need, since in 1.0 RedisAI plugin was initialized with MODULE_LOADED event (without locking the GIL explicitly).

**Comment by MeirShpilraien** [comment]
So why it was changed?

**Comment by alonre24** [comment]
good question. @DvirDukhan Do you remember?

**Comment by DvirDukhan** [comment]
I believe it was part of #461 
moved from `RedisGears_OnModuleLoad` to redisgears_python
@MeirShpilraien thought?

**Comment by MeirShpilraien** [comment]
Ohh right I remembered now, we need to expose this API to plugin.

**Pull request merged**
