### PR TITLE
Adds versioned docs

### PR DESCRIPTION
**Pull request by itamarhaber**

### CODE REVIEW

**Comment by MeirShpilraien** [comment]
The failure:
```
no cluster on oss
./run_tests.sh: line 24: RLTest: command not found
make: *** [Makefile:349: test] Error 127
```
@rafie any idea why it failed

**Comment by rafie** [comment]
Not synced with master: uses RLTest rather than python -m RLTest.

**Comment by MeirShpilraien** [comment]
@rafie notice that this is 0.9, what changed? we can not build 0.9 branch?

**Comment by rafie** [comment]
0.9 is quite old. We don't regularly build it. It uses the old rmbuilder, which I don't want to support. I think we should align with master.

**Comment by MeirShpilraien** [comment]
@rafie this is 0.9, we can not merge master into it

**Comment by rafie** [comment]
@MeirShpilraien We can merge the small fixes that needed for the CircleCI build to pass.

**Pull request merged**
