### PR TITLE
Avoid --fail-fast on benchmarks. Include tags triggering

### PR DESCRIPTION
**Pull request by filipecosta90**
With `--fail-fast` mode we stop all benchmarks at the first error. Given the benchmark suite of RedisGears is quite simple I suggest we remove this and let the benchmark tool to try to trigger other benchmarks even in the case of some failure. In that manner we'll at least have partial performance data and logs to analyze what happened and confirm if it's test related or env/tool related.

### CODE REVIEW

**Comment by MeirShpilraien** [comment]
Thanks @filipecosta90, can you please update the top comment and explain why this change is needed (the removal of fail-fats)?

**Comment by filipecosta90** [comment]
> Thanks @filipecosta90, can you please update the top comment and explain why this change is needed (the removal of fail-fats)?

done @MeirShpilraien :)

**Comment by MeirShpilraien** [comment]
@filipecosta90 wouldn't this has a potential of hiding issues?

**Comment by filipecosta90** [comment]
> @filipecosta90 wouldn't this has a potential of hiding issues?

Nope. it will still fail the benchmarks. The big difference is that it will try to collect more data...

**Review by MeirShpilraien — APPROVED** [review]

**Comment by filipecosta90** [comment]
Closing in favor of #995

**Pull request closed without merging**
