### PR TITLE
Extend time before failing due to lack of output

### PR DESCRIPTION
**Pull request by rafie**

### CODE REVIEW

**Comment by MeirShpilraien** [comment]
@rafie why are you changing this change? I do not think we should reach so much time without output ..

**Comment by rafie** [comment]
@MeirShpilraien It's probably only a macOS thing, and the built-in timeout (20m) is a magic number. If it's really stuck, it will fail over the 30m limit as well.

**Comment by MeirShpilraien** [comment]
Yes but then we will have to wait 30 minutes. Regarding the failure yesterday, as I wrote on slack, it was really stuck and there is a bug there ..

**Comment by rafie** [comment]
It may be a bug but the test does not fail consistently. I'll try to reproduce it on a non-CircleCI mac machine.

**Comment by MeirShpilraien** [comment]
@rafie can we close this one?

**Pull request closed without merging**
